package view;

/**
 *
 * @author Miguel Maria Vazquez Martinez
 */
public class AboutPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    public AboutPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLicense = new javax.swing.JLabel();
        labelAuthors = new javax.swing.JLabel();
        labelVersionTitle = new javax.swing.JLabel();
        labelLicenseTitle = new javax.swing.JLabel();
        labelAuthor1 = new javax.swing.JLabel();
        LabelAuthor2 = new javax.swing.JLabel();
        labelVersion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        labelLicense.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLicense.setText("https://creativecommons.org/licenses/by-nc-nd/4.0/");
        labelLicense.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelAuthors.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelAuthors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAuthors.setText("CREADORES");
        labelAuthors.setFocusable(false);
        labelAuthors.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelVersionTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelVersionTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVersionTitle.setText("VERSIÓN");

        labelLicenseTitle.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        labelLicenseTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLicenseTitle.setText("LICENCIA");

        labelAuthor1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelAuthor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAuthor1.setText("David Bernal Navarrete");

        LabelAuthor2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        LabelAuthor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAuthor2.setText("Miguel María Vázquez Martínez");

        labelVersion.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        labelVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVersion.setText("Version?");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\ccIcon.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jLabel1))
                    .addComponent(labelLicenseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(labelLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelAuthor2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVersionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelAuthors, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelAuthor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelAuthor2)
                .addGap(50, 50, 50)
                .addComponent(labelVersionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelVersion)
                .addGap(50, 50, 50)
                .addComponent(labelLicenseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAuthor2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelAuthor1;
    private javax.swing.JLabel labelAuthors;
    private javax.swing.JLabel labelLicense;
    private javax.swing.JLabel labelLicenseTitle;
    private javax.swing.JLabel labelVersion;
    private javax.swing.JLabel labelVersionTitle;
    // End of variables declaration//GEN-END:variables
}
