/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author migva
 */

import controller.List;

public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form JFrameMain
     */
    public FrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        mainMenuBar = new javax.swing.JMenuBar();
        menuButton = new javax.swing.JMenu();
        loadListButton = new javax.swing.JMenuItem();
        saveListButton = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        addAnalistButton = new javax.swing.JMenuItem();
        addProgrammerButton = new javax.swing.JMenuItem();
        listButton = new javax.swing.JMenu();
        navButton = new javax.swing.JMenu();
        aboutButton = new javax.swing.JMenu();

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación");
        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setName("JFrameMain"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        mainMenuBar.setBackground(new java.awt.Color(204, 204, 204));
        mainMenuBar.setForeground(new java.awt.Color(0, 0, 0));
        mainMenuBar.setPreferredSize(new java.awt.Dimension(222, 40));

        menuButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\menuIcon.png")); // NOI18N
        menuButton.setText("Menú");

        loadListButton.setBackground(new java.awt.Color(204, 204, 204));
        loadListButton.setForeground(new java.awt.Color(0, 0, 0));
        loadListButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\openIcon.png")); // NOI18N
        loadListButton.setText("Cargar Lista");
        menuButton.add(loadListButton);

        saveListButton.setBackground(new java.awt.Color(204, 204, 204));
        saveListButton.setForeground(new java.awt.Color(0, 0, 0));
        saveListButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\saveIcon.png")); // NOI18N
        saveListButton.setText("Guardar Lista");
        menuButton.add(saveListButton);

        mainMenuBar.add(menuButton);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\addIcon.png")); // NOI18N
        jMenu1.setText("Añadir");

        addAnalistButton.setBackground(new java.awt.Color(204, 204, 204));
        addAnalistButton.setForeground(new java.awt.Color(0, 0, 0));
        addAnalistButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\emptyIcon.png")); // NOI18N
        addAnalistButton.setText("Analista");
        jMenu1.add(addAnalistButton);

        addProgrammerButton.setBackground(new java.awt.Color(204, 204, 204));
        addProgrammerButton.setForeground(new java.awt.Color(0, 0, 0));
        addProgrammerButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\emptyIcon.png")); // NOI18N
        addProgrammerButton.setText("Programador");
        jMenu1.add(addProgrammerButton);

        mainMenuBar.add(jMenu1);

        listButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\listIcon.png")); // NOI18N
        listButton.setText("Listar");
        listButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listButtonMouseClicked(evt);
            }
        });
        mainMenuBar.add(listButton);

        navButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\navIcon.png")); // NOI18N
        navButton.setText("Navegar");
        mainMenuBar.add(navButton);

        aboutButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P04\\PMDM_P04_JAVA\\VazquezMartinezMiguel_BernalNavarreteDavid_JAVA04\\images\\infoIcon.png")); // NOI18N
        aboutButton.setText("Sobre App");
        mainMenuBar.add(aboutButton);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listButtonMouseClicked
        this.setContentPane(listPanel);
        this.pack();
        
    }//GEN-LAST:event_listButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrameMain().setVisible(true);
            }
        });
    }
    
    public static List getMainList(){return myList;}
    
    
    // Attributes //////////////////////////////////////////////////////////////
    private static List myList = new List();
    private ListPanel listPanel = new ListPanel();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutButton;
    private javax.swing.JMenuItem addAnalistButton;
    private javax.swing.JMenuItem addProgrammerButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu listButton;
    private javax.swing.JMenuItem loadListButton;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenu menuButton;
    private javax.swing.JMenu navButton;
    private javax.swing.JMenuItem saveListButton;
    // End of variables declaration//GEN-END:variables
}
