/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.List;
import javax.swing.DefaultListModel;
import model.*;

/**
 *
 * @author migva
 */
public class ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    public ListPanel() {
        initComponents();
    }
    
    private DefaultListModel modeloLista()
    {
        
        DefaultListModel<String> modelo = new DefaultListModel<>();
        myList.resetCurrent();
        
        do{
            Employee emp = (Employee) myList.getCurrent().getData();
            if (emp instanceof Analyst adv){
                String infoObjeto = "A " + adv.toString();
                modelo.addElement(infoObjeto);  

            }else if (emp instanceof Programmer adv){
                String infoObjeto = "T " + adv.toString();
                modelo.addElement(infoObjeto);             
            }else{
                modelo.addElement("No hay elementos");
            }
            myList.moveForward();
        }while(myList.getCurrent() != myList.getEndList());
        return modelo;
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPanelScroll = new javax.swing.JScrollPane();
        listPanelJList = new javax.swing.JList<>();

        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        listPanelScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listPanelJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1 | Item1.1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 6", "Item 7", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item ", "Item " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPanelJList.setMaximumSize(new java.awt.Dimension(400, 200));
        listPanelJList.setMinimumSize(new java.awt.Dimension(400, 200));
        listPanelJList.setPreferredSize(new java.awt.Dimension(400, 300));
        listPanelScroll.setViewportView(listPanelJList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(listPanelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(listPanelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
    }// </editor-fold>//GEN-END:initComponents

    private final List myList = FrameMain.getMainList();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> listPanelJList;
    private javax.swing.JScrollPane listPanelScroll;
    // End of variables declaration//GEN-END:variables
}
