/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.List;
import javax.swing.DefaultListModel;
import model.*;

/**
 *
 * @author migva
 */
public class ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form MenuPanel
     */
    public ListPanel() {
        initComponents();
        listPanelJList.setModel(modelList());
    }
    
    private DefaultListModel modelList()
    {
        DefaultListModel<String> model = new DefaultListModel<>();
        
        if(myList.getHeadList() == null){
            model.addElement("No hay elementos");
        }else{
            model.removeAllElements();
            myList.currentToHead();
            
            model.addElement(myList.getCurrent().getData().toString());  
            
            do{

                myList.moveForward();
                model.addElement(myList.getCurrent().getData().toString());  
         
            }while(myList.getCurrent() != myList.getEndList());            
        }
        
        return model;
    }       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPanelScroll = new javax.swing.JScrollPane();
        listPanelJList = new javax.swing.JList<>();

        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        listPanelScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        listPanelJList.setMaximumSize(new java.awt.Dimension(400, 200));
        listPanelJList.setMinimumSize(new java.awt.Dimension(400, 200));
        listPanelJList.setPreferredSize(new java.awt.Dimension(400, 300));
        listPanelScroll.setViewportView(listPanelJList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(listPanelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(listPanelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
    }// </editor-fold>//GEN-END:initComponents

    private final List myList = FrameMain.getMainList();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> listPanelJList;
    private javax.swing.JScrollPane listPanelScroll;
    // End of variables declaration//GEN-END:variables
}
