package view;

/**
 *
 * @author Miguel Maria Vazquez Martinez
 * @author David Bernal Navarrete
 * 
 */

import javax.swing.*;

public class SortJDialog extends JDialog {

    /**
     * Creates new form warningJDialog This class create a window to inform the
     * user about an error in the program execution.
     */
    
    // CONSTRUCTOR /////////////////////////////////////////////////////////////
    public SortJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortJPanel = new javax.swing.JPanel();
        listLabelSortDialog = new javax.swing.JLabel();
        messageListSortDialog = new javax.swing.JLabel();
        arryListLabelSortDialog = new javax.swing.JLabel();
        messageArrayListSortDialog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ERROR");

        sortJPanel.setBackground(new java.awt.Color(255, 255, 255));

        listLabelSortDialog.setBackground(new java.awt.Color(255, 255, 255));
        listLabelSortDialog.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        listLabelSortDialog.setForeground(new java.awt.Color(0, 0, 0));
        listLabelSortDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        listLabelSortDialog.setText("Tiempo de filtrado de List:");

        messageListSortDialog.setBackground(new java.awt.Color(255, 255, 255));
        messageListSortDialog.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        messageListSortDialog.setForeground(new java.awt.Color(0, 0, 0));
        messageListSortDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageListSortDialog.setText("MESSAGE");

        arryListLabelSortDialog.setBackground(new java.awt.Color(255, 255, 255));
        arryListLabelSortDialog.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        arryListLabelSortDialog.setForeground(new java.awt.Color(0, 0, 0));
        arryListLabelSortDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arryListLabelSortDialog.setText("Tiempo de filtrado de ArrayList:");

        messageArrayListSortDialog.setBackground(new java.awt.Color(255, 255, 255));
        messageArrayListSortDialog.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        messageArrayListSortDialog.setForeground(new java.awt.Color(0, 0, 0));
        messageArrayListSortDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageArrayListSortDialog.setText("MESSAGE");

        javax.swing.GroupLayout sortJPanelLayout = new javax.swing.GroupLayout(sortJPanel);
        sortJPanel.setLayout(sortJPanelLayout);
        sortJPanelLayout.setHorizontalGroup(
            sortJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(sortJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(messageArrayListSortDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arryListLabelSortDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageListSortDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listLabelSortDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        sortJPanelLayout.setVerticalGroup(
            sortJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sortJPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(listLabelSortDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(messageListSortDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(arryListLabelSortDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(messageArrayListSortDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(sortJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(sortJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setMessageSorted(String miliList, String miliArrayList) {
        this.listLabelSortDialog.setText("Tiempo de filtrado de List:");
        this.messageListSortDialog.setText(miliList + " milisegundos.");
        this.arryListLabelSortDialog.setText("Tiempo de filtrado de ArrayList:");
        this.messageArrayListSortDialog.setText(miliArrayList + " milisegundos.");
    }

    public void setInformation(String message){
        this.listLabelSortDialog.setText("");
        this.messageListSortDialog.setText("INFORMACIÓN");
        this.arryListLabelSortDialog.setText(message);
        this.messageArrayListSortDialog.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arryListLabelSortDialog;
    private javax.swing.JLabel listLabelSortDialog;
    private javax.swing.JLabel messageArrayListSortDialog;
    private javax.swing.JLabel messageListSortDialog;
    private javax.swing.JPanel sortJPanel;
    // End of variables declaration//GEN-END:variables
}
