package view;
/**
 *
 * @author Miguel Maria Vazquez Martinez
 */

import javax.swing.*;

public class warningJDialog extends JDialog {

    /**
     * Creates new form warningJDialog
     * This class create a window to inform the user about an error in the program execution.
     */
    // CONSTRUCTOR /////////////////////////////////////////////////////////////
    public warningJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warningJPanel = new javax.swing.JPanel();
        message = new javax.swing.JLabel();
        warningImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ERROR");

        warningJPanel.setBackground(new java.awt.Color(255, 255, 255));

        message.setBackground(new java.awt.Color(255, 255, 255));
        message.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        message.setForeground(new java.awt.Color(163, 0, 17));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("MESSAGE");

        warningImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\migva\\Google Drive\\08 DAM\\2 Curso\\02 PMDM\\P03\\VazquezMartinezMiguelMariaJAVA03\\WarningLogo.png")); // NOI18N

        javax.swing.GroupLayout warningJPanelLayout = new javax.swing.GroupLayout(warningJPanel);
        warningJPanel.setLayout(warningJPanelLayout);
        warningJPanelLayout.setHorizontalGroup(
            warningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningJPanelLayout.createSequentialGroup()
                .addGroup(warningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(warningJPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(warningImage, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(warningJPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        warningJPanelLayout.setVerticalGroup(
            warningJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(warningJPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(warningImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(warningJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(warningJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void setMessage(String message){
        this.message.setText(message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel message;
    private javax.swing.JLabel warningImage;
    private javax.swing.JPanel warningJPanel;
    // End of variables declaration//GEN-END:variables
}
